spring:
  # 数据源配置
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/game_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: GameHikariCP-Master
    slave:
      jdbc-url: jdbc:mysql://localhost:3307/game_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: GameHikariCP-Slave

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        # 数据库方言
        dialect: org.hibernate.dialect.MySQLDialect
        # 格式化SQL
        format_sql: true
        # 批量操作
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        # 查询优化
        order_inserts: true
        order_updates: true
        # 二级缓存
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    # 显示SQL
    show-sql: false

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000ms

  # 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=30m,expireAfterAccess=15m,recordStats

# Flyway配置
flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  validate-on-migrate: true
  clean-disabled: true

# 日志配置
logging:
  level:
    com.game.frame.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG