apiVersion: v1
kind: Namespace
metadata:
  name: game-server
  labels:
    name: game-server
    environment: production

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-config
  namespace: game-server
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      cloud:
        nacos:
          discovery:
            server-addr: nacos-service:8848
            namespace: game-server
            group: DEFAULT_GROUP
          config:
            server-addr: nacos-service:8848
            namespace: game-server
            group: DEFAULT_GROUP
            file-extension: yml
      redis:
        host: redis-service
        port: 6379
        timeout: 3000
        lettuce:
          pool:
            max-active: 20
            max-wait: -1
            max-idle: 10
            min-idle: 5
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
    
    logging:
      level:
        com.game: INFO
        org.springframework: WARN
        org.apache.dubbo: WARN
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

---
apiVersion: v1
kind: Secret
metadata:
  name: game-secrets
  namespace: game-server
type: Opaque
data:
  # Base64 encoded secrets
  mysql-password: cGFzc3dvcmQxMjM=  # password123
  redis-password: ""  # No password for development
  jwt-secret: Z2FtZS1zZXJ2ZXItand0LXNlY3JldC0yMDI1  # game-server-jwt-secret-2025

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-service-account
  namespace: game-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: game-server
  name: game-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-service-role-binding
  namespace: game-server
subjects:
- kind: ServiceAccount
  name: game-service-account
  namespace: game-server
roleRef:
  kind: Role
  name: game-service-role
  apiGroup: rbac.authorization.k8s.io